sonar.projectKey=diplomado-devops-backend
sonar.projectName=diplomado-devops-backend

sonar.sources=github/backend
sonar.tests=github/backend/tests

sonar.python.coverage.reportPaths=github/backend/coverage.xml

sonar.sourceEncoding=UTF-8