Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "jenkins-and-octopus-dt"

  config.vm.network "forwarded_port",
    guest: 8080,
    host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.name = "jenkins-and-octopus-dt"
    vb.memory = 1024
    vb.cpus = 1
  end

  # Instala Docker dentro de la VM
  config.vm.provision "docker"

  # Instala Jenkins
  config.vm.provision "shell",
    path: "scripts/install-jenkins.sh"

  # Instala Octopus Tentacle
  config.vm.provision "shell",
    path: "scripts/install-octopus-tentacle.sh"
end
