Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "github-runner"
  
  config.vm.network "forwarded_port",
    guest: 8080,
    host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.name = "github-runner"
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Instala Docker dentro de la VM
  config.vm.provision "docker"

  # Instala dependencias para el GitHub Actions Runner
  config.vm.provision "shell",
    path: "scripts/install-github-runner.sh"
end
