name: Continuous Integration

on:
  push:

env:
  DOCKERHUB_USERNAME: brendisas

jobs:
  
  code:
    name: Code
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build database
        uses: docker/build-push-action@v6
        with:
          context: ./db
          push: false
          tags: ${{ env.DOCKERHUB_USERNAME }}/database:${{ github.sha }}

      - name: Build backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          tags: ${{ env.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
      
      - name: Build frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: false
          tags: ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}

  test:
    name: Test
    runs-on: [self-hosted]
    needs: build

    steps:
      - name: Test frontend
        run: docker image inspect ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}

      - name: Test backend
        run: docker image inspect ${{ env.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

      - name: Test database
        run: docker image inspect ${{ env.DOCKERHUB_USERNAME }}/database:${{ github.sha }}

  release:
    name: Release
    runs-on: [self-hosted]
    needs: test

    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}

    steps:
      - name: Set image tag
        id: set_tag
        run: echo "image_tag=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"

      - name: Tag images with date version
        run: |
          docker tag ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }} ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ steps.set_tag.outputs.image_tag }}
          docker tag ${{ env.DOCKERHUB_USERNAME }}/backend:${{ github.sha }} ${{ env.DOCKERHUB_USERNAME }}/backend:${{ steps.set_tag.outputs.image_tag }}
          docker tag ${{ env.DOCKERHUB_USERNAME }}/database:${{ github.sha }} ${{ env.DOCKERHUB_USERNAME }}/database:${{ steps.set_tag.outputs.image_tag }}

      - name: Tag images with last version
        run: |
          docker tag ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ steps.set_tag.outputs.image_tag }} ${{ env.DOCKERHUB_USERNAME }}/frontend:latest
          docker tag ${{ env.DOCKERHUB_USERNAME }}/backend:${{ steps.set_tag.outputs.image_tag }} ${{ env.DOCKERHUB_USERNAME }}/backend:latest
          docker tag ${{ env.DOCKERHUB_USERNAME }}/database:${{ steps.set_tag.outputs.image_tag }} ${{ env.DOCKERHUB_USERNAME }}/database:latest

  push:
    name: Push to Docker Hub
    runs-on: [self-hosted]
    needs: release

    env:
      IMAGE_TAG: ${{ needs.release.outputs.image_tag }}

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push frontend
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ env.IMAGE_TAG }}
          docker push ${{ env.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Push backend
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/backend:${{ env.IMAGE_TAG }}
          docker push ${{ env.DOCKERHUB_USERNAME }}/backend:latest

      - name: Push database
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/database:${{ env.IMAGE_TAG }}
          docker push ${{ env.DOCKERHUB_USERNAME }}/database:latest